current_dir := ${CURDIR}
TOP := top

DEVICE := xc7z020_test
BITSTREAM_DEVICE := artix7
PARTNAME := xc7z020clg400-1
# OFL_BOARD := ??? snickerdoodle ???

SOURCES := ${current_dir}/driver.vhdl

include ${current_dir}/common.mk
